function f(a){return function(){return this[a]}}var k;function aa(a,b,c){return a.call.apply(a.bind,arguments)}function ba(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}
function l(a,b,c){l=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?aa:ba;return l.apply(null,arguments)}function m(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}}function p(a,b){function c(){}c.prototype=b.prototype;a.ua=b.prototype;a.prototype=new c};function ca(){this.ga=!1;this.G=da;this.V=null;this.P=[];this.Q=[];this.T=[];this.O=[];this.sa=[]}var da=6,ea=window.requestAnimationFrame||window.webkitRequestAnimationFrame;function r(a,b){a.O.push(b);4<a.G&&fa(a)}function fa(a){if(!a.ga&&null==a.V){var b=l(a.la,a);a.V=ea.call(window,b)}}
ca.prototype.la=function(){this.V=null;this.G=1;for(var a=0;a<this.P.length;a++)this.P[a]();this.P=[];this.G=2;for(a=0;a<this.Q.length;a++)this.Q[a]();this.Q=[];this.G=3;for(a=0;a<this.T.length;a++)this.T[a]();this.T=[];this.G=4;for(a=0;a<this.O.length;a++)this.O[a]();this.O=[];this.G=da};function s(a){Error.captureStackTrace?Error.captureStackTrace(this,s):this.stack=Error().stack||"";a&&(this.message=String(a))}p(s,Error);s.prototype.name="CustomError";function ga(a,b){for(var c=a.split("%s"),d="",e=Array.prototype.slice.call(arguments,1);e.length&&1<c.length;)d+=c.shift()+e.shift();return d+c.join("%s")};function t(a,b){b.unshift(a);s.call(this,ga.apply(null,b));b.shift();this.ra=a}p(t,s);t.prototype.name="AssertionError";function u(a,b){throw new t("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};function ha(a){this.ma=a;this.aa={};this.$=[];this.fa={};this.ba=l(this.ia,this)}function ia(a){var b=ja;b.$.push(a);for(var c in b.aa)a.addEventListener(c,b.ba,!1)}ha.prototype.ia=function(a){for(var b=this.fa[a.type],c=0;c<b.length;c++){var d=b[c],e=a.target;(e.matches||e.webkitMatchesSelector||e.mozMatchesSelector||e.msMatchesSelector).call(e,d.ta)&&(e=l(d.qa,d.scope,a),d.va?e():(d=this.ma,d.P.push(e),1<d.G&&fa(d)))}};var v=new ca,ja=new ha(v),w={};function ka(a,b,c){a=new window.ArrayObserver(a,b);w[c]=a}function la(a){w[a].disconnect();delete w[a]}var x={};function ma(){return!0};var y="area base br col command embed hr img input keygen link meta param source track wbr".split(" "),z="ifempty elseif else case default view".split(" "),B="foreach ifempty if elseif else switch case default view".split(" "),na={root:[{c:RegExp("\\s*<("+y.join("|")+")","g"),b:[1],push:["tag_def"]},{c:/\s*<([a-z]+)/g,b:[1],push:["tag_or_command_or_text","tag_def"]},{c:/\s*/g,b:[],pop:!0}],tag_def:[{c:/\s+([a-zA-Z_:][-a-zA-Z0-9_:.]+)\s*=\s*"/g,b:[4],push:["attr"]},{c:/\s+([a-zA-Z_:][-a-zA-Z0-9_:.]+)/g,
b:[4,6]},{c:RegExp("\\s+{("+B.join("|")+")","g"),b:[7],push:["attr_command_outer","command_def"]},{c:/\s*\/>/g,b:[2],pop:!0},{c:/\s*>/g,b:[2],pop:!0}],tag_or_command_or_text:[{c:RegExp("\\s*<("+y.join("|")+")","g"),b:[1],push:["tag_def"]},{c:/\s*<([a-z]+)/g,b:[1],push:["tag_or_command_or_text","tag_def"]},{c:/\s*<\/([a-z]+)>/g,b:[3],pop:!0},{c:/\s*{(view)/g,b:[7],push:["view_command_def"]},{c:RegExp("\\s*{("+z.join("|")+")","g"),b:[7],push:["command_def"]},{c:RegExp("\\s*{("+B.join("|")+")","g"),
b:[7],push:["tag_or_command_or_text","command_def"]},{c:/\s*{\/([a-z]+)}/g,b:[9],pop:!0},{c:/\s*(?={[lr]b})/g,b:[17],push:["text"]},{c:/\s*(?={\$)/g,b:[17],push:["text"]},{c:/\s*(?=[^<{])/g,b:[17],push:["text"]}],attr_command_outer:[{c:/\s*([a-zA-Z_:][-a-zA-Z0-9_:.]+)\s*=\s*"/g,b:[4],push:["attr"]},{c:/\s*([a-zA-Z_:][-a-zA-Z0-9_:.]+)/g,b:[4,6]},{c:/\s*{\/([a-z]+)}/g,b:[9],pop:!0}],attr_command:[{c:/{(rb|lb)}/g,b:[7]},{c:RegExp("\\s*{("+z.join("|")+")","g"),b:[7],push:["command_def"]},{c:RegExp("\\s*{("+
B.join("|")+")","g"),b:[7],push:["attr_command","command_def"]},{c:/{(\$[a-zA-Z]+(?:\.[a-zA-Z]+)*)}/g,b:[20]},{c:/{\/([a-z]+)}/g,b:[9],pop:!0},{c:/(.*?)(?={)/g,b:[5]}],attr:[{c:/{(rb|lb)}/g,b:[7]},{c:RegExp("{("+z.join("|")+")","g"),b:[7],push:["command_def"]},{c:RegExp("{("+B.join("|")+")","g"),b:[7],push:["attr_command","command_def"]},{c:/{(\$[a-zA-Z]+(?:\.[a-zA-Z]+)*)}/g,b:[20]},{c:/([^"]*?)(?={)/g,b:[5]},{c:/([^"]+?)(?=")/g,b:[5]},{c:/"/g,b:[6],pop:!0}],text:[{c:/{(rb|lb)}/g,b:[7]},{c:/{(\$[a-zA-Z]+(?:\.[a-zA-Z]+)*)}/g,
b:[20]},{c:/\s*(?=<)/g,b:[19],pop:!0},{c:/([^<{]+?)(?=(?:(?:{\$)|(?:{[lr]b})))/g,b:[18]},{c:/\s*(?={)/g,b:[19],pop:!0},{c:/(.*?)\s*(?=[<{])/g,b:[18]}],view_command_def:[{c:/\s+([a-zA-Z]+(?:\.[a-zA-Z]+)*)/g,b:[21]},{c:/\s*(\$[a-zA-Z]+(?:\.[a-zA-Z]+)*)/g,b:[12]},{c:/\s*}/g,b:[8],pop:!0}],command_def:[{c:/\s+(?!})/g,b:[10],push:["expression"]},{c:/\s*}/g,b:[8],pop:!0}],expression:[{c:/\s*(?=})/g,b:[16],pop:!0},{c:RegExp("\\s*(null|true|false)","g"),b:[11]},{c:/\s*(-?(?:(?:[0-9]+\.[0-9]+)|(?:(?:0x)?[0-9]+)|(?:\.[0-9]+))(?:e-?[0-9]+)?)/g,
b:[13]},{c:/\s*'((?:(?=(\\?))\2.)*?)'/g,b:[14]},{c:/\s*(\$[a-zA-Z]+(?:\.[a-zA-Z]+)*)/g,b:[12]},{c:RegExp("\\s*(!=|!|\\*|/|%|\\+|-|<=|>=|<|>|==|&&|\\|\\||\\(|\\)|in)","g"),b:[15]}]};var oa=Array.prototype,pa=oa.indexOf?function(a,b,c){return oa.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if("string"==typeof a)return"string"==typeof b&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};function C(a){this.da=a;this.attributes=[];this.children=[]}function D(){this.l=[];this.e=[]}function E(a){this.name=a;this.l=[];this.e=[]}function F(){this.p=[];this.e=[]}function qa(){this.C=null;this.children=[]}function G(){this.C=null;this.e=[]}function H(){this.children=[];this.U=[];this.pa=this.X="";this.h=null}function ra(){this.view="";this.h=null}
function sa(a,b){for(var c=!1;!c;){var d=b.shift();switch(d.type){case 4:d=new E(d.value);a.attributes.push(d);ta(d,b);break;case 7:"if"==d.value?(b.unshift(d),d=new F,a.attributes.push(d),I(d,b)):"switch"==d.value?(d=new F,a.attributes.push(d),J(d,b)):u("Invalid command.");break;case 2:0<=pa(y,a.da)||ua(a.children,b);c=!0;break;default:u("Invalid token.")}}}
function ua(a,b){for(var c=!1;!c;){var d=b.shift();switch(d.type){case 1:d=new C(d.value);a.push(d);sa(d,b);break;case 17:d=new D;a.push(d);va(d,b);break;case 3:c=!0;break;case 7:"if"==d.value?(b.unshift(d),d=new F,a.push(d),I(d,b)):"switch"==d.value?(d=new F,a.push(d),J(d,b)):"foreach"==d.value?(d=new H,a.push(d),wa(d,b)):"ifempty"==d.value?(b.unshift(d),c=!0):"view"==d.value?(d=new ra,a.push(d),xa(d,b)):u("Unexpected COMMAND token: "+d.value+" in tag.");break;case 9:"foreach"==d.value?c=!0:u("Unexpected COMMAND_END token: "+
d.value+" in tag.")}}}function ta(a,b){for(var c=!1;!c;){var d=b.shift();switch(d.type){case 7:if("if"==d.value){b.unshift(d);var e=new F;a.l.push(e);I(e,b)}else"switch"==d.value?(e=new F,a.l.push(e),J(e,b)):"rb"==d.value?a.l.push("}"):"lb"==d.value?a.l.push("{"):u("Invalid command inside of an attribute.");break;case 5:a.l.push(d.value);break;case 20:e=new G;ya(e,d.value);a.l.push(e);break;case 6:za(a.l,a.e),c=!0}}}
function za(a,b){for(var c=0;c<a.length;c++){var d=a[c];if(d instanceof F){Array.prototype.push.apply(b,d.e);for(var e=0;e<d.p.length;e++)za(d.p[e].children,b)}else d instanceof G&&Array.prototype.push.apply(b,d.e)}}function I(a,b){for(var c=!1;!c;)switch(b.shift().type){case 7:var d=new qa;a.p.push(d);Aa(d,b,a.e);Ba(d,b);break;case 9:c=!0}}
function J(a,b){var c=!1,d=b.shift(),d=b.shift();Ca(a.e,d.value.substring(1).split("."));var e=d.value.substring(1);b.shift();for(b.shift();!c;)switch(d=b.shift(),d.type){case 7:d=new qa;a.p.push(d);Aa(d,b,[],e);Ba(d,b);break;case 9:c=!0}}function ya(a,b){a.C=Da(b);Ca(a.e,b.substring(1).split("."))}
function wa(a,b){var c=b.shift(),c=b.shift();a.X=c.value.substring(1);b.shift();c=b.shift();a.h=c.value.substring(1).split(".");b.shift();b.shift();ua(a.children,b);7==b[0].type&&(b.shift(),ua(a.U,b))}function Aa(a,b,c,d){var e=!1;for(a.C=ma;!e;)switch(b.shift().type){case 10:Ea(a,b,c,d);break;case 8:e=!0}}
function Ba(a,b){for(var c=!1;!c;){var d=b.shift();switch(d.type){case 7:if("if"==d.value){b.unshift(d);var e=new F;a.children.push(e);I(e,b)}else"switch"==d.value?(e=new F,a.children.push(e),J(e,b)):"foreach"==d.value?(e=new H,a.children.push(e),wa(e,b)):"lb"==d.value?a.children.push("{"):"rb"==d.value?a.children.push("}"):"view"==d.value?(e=new ra,a.children.push(e),xa(e,b)):(b.unshift(d),c=!0);break;case 4:d=new E(d.value);a.children.push(d);ta(d,b);break;case 1:e=new C(d.value);a.children.push(e);
sa(e,b);break;case 17:e=new D;a.children.push(e);va(e,b);break;case 5:a.children.push(d.value);break;case 20:e=new G;ya(e,d.value);a.children.push(e);break;case 9:b.unshift(d),c=!0}}}
function va(a,b){for(var c=!1;!c;){var d=b.shift();switch(d.type){case 7:"rb"==d.value?a.l.push("}"):"lb"==d.value?a.l.push("{"):u("Invalid command for text node: "+d.value);break;case 20:var e=new G;ya(e,d.value);a.l.push(e);Array.prototype.push.apply(a.e,e.e);break;case 18:a.l.push(d.value);break;case 19:c=!0;break;default:u("Invalid token.")}}}
function Ea(a,b,c,d){for(var e=!1,g=[];!e;){var h=b.shift();switch(h.type){case 15:case 11:case 13:g.push(h.value);break;case 14:g.push("'"+h.value+"'");break;case 12:h=h.value.substring(1);Ca(c,h.split("."));g.push("data."+h);break;case 16:e=!0}}a.C=d?eval("(function(data) { return data."+d+" == "+g.join(" ")+"; })"):eval("(function(data) { return "+g.join(" ")+"; })")}
function xa(a,b){var c=b.shift();a.view=c.value;c=b.shift();switch(c.type){case 12:a.h=c.value.substring(1).split("."),b.shift()}}function Da(a){return eval("(function(data) { return data."+a.substring(1)+"; })")}function Ca(a,b){for(var c=!1,d=b.join("."),e=0;e<a.length;e++)if(a[e].join(".")==d){c=!0;break}c||a.push(b)};function Fa(a){var b={},c;for(c in a)b[c]=a[c];return b};var Ga={};function Ha(){}function K(a,b){this.parent=a;this.F=b}p(K,Ha);function L(a,b){this.d=a;this.u=b;this.S=document.createAttribute(a.name);this.o=m(Ia,a.l,b);this.g=!1;this.q=[]}L.prototype.observe=function(){this.S.value=this.o();l(this.r,this);for(var a=0;a<this.d.e.length;a++)this.q.push(M(this.d.e[a]))};L.prototype.n=function(){for(var a=0;a<this.d.e.length;a++)N(this.d.e[a]);this.q=[]};L.prototype.getAttributeNode=f("S");
L.prototype.r=function(){this.g||(this.g=!0,r(v,l(function(){this.g=!1;this.S.value=this.o()},this)))};function Ia(a,b){for(var c=[],d=0;d<a.length;d++){var e=a[d];if("string"==typeof e)c.push(e);else if(e instanceof G)c.push(e.C(b));else if(e instanceof F){if(e=e.p[Ja(e,b)])for(var g=0;g<e.children.length;g++){var h=Ia(e.children,b);h&&c.push(h)}}else u("Invalid node for attribute: "+typeof e)}return c.join("")}
function O(a,b,c){this.d=a;this.u=b;this.o=m(Ja,a,b);this.K=c;this.f=[];for(c=0;c<a.p.length;c++){var d=a.p[c];this.f[c]=[];for(var e=0;e<d.children.length;e++)this.f[c][e]=new L(d.children[e],b)}this.k=null;this.g=!1;this.q=[]}p(O,Ha);O.prototype.observe=function(){for(var a=0;a<this.f.length;a++)for(var b=0;b<this.f[a].length;b++)this.f[a][b].observe();Ka(this);l(this.r,this);for(a=0;a<this.d.e.length;a++)this.q.push(M(this.d.e[a]))};
O.prototype.n=function(){for(var a=0;a<this.d.e.length;a++)N(this.d.e[a]);this.q=[];for(a=0;a<this.f.length;a++)for(var b=0;b<this.f[a].length;b++)this.f[a][b].n()};O.prototype.r=function(){this.g||(this.g=!0,r(v,l(function(){this.g=!1;Ka(this)},this)))};function Ka(a){var b=a.o(),c=a.K.v();if(b!=a.k){if(null!=a.k)for(var d=a.f[a.k],e=0;e<d.length;e++)c.removeAttributeNode(d[e].getAttributeNode());if(null!=b)for(d=a.f[b],e=0;e<d.length;e++)c.setAttributeNode(d[e].getAttributeNode());a.k=b}}
function S(a,b,c,d){K.call(this,c,d);this.A=document.createElement(a.da);this.a=[];this.B=[];for(c=0;c<a.attributes.length;c++){var e=a.attributes[c];e instanceof E?(this.B.push(new L(e,b)),this.A.setAttributeNode(this.B[c].getAttributeNode())):e instanceof F?this.B.push(new O(e,b,this)):u("Invalid node for attribute: "+typeof e)}e=[];for(c=0;c<a.children.length;c++){var g=a.children[c];this.a[c]=new (T(g))(g,b,this,d);Array.prototype.push.apply(e,this.a[c].m())}}p(S,K);k=S.prototype;
k.observe=function(){for(var a=[],b=0;b<this.a.length;b++)this.a[b].observe(),Array.prototype.push.apply(a,this.a[b].m());for(b=0;b<this.B.length;b++)this.B[b].observe();for(;b=this.A.firstChild;)this.A.removeChild(b);0<a.length&&this.w(this.a[this.a.length-1],a)};k.n=function(){for(var a=0;a<this.a.length;a++)this.a[a].n();for(a=0;a<this.B.length;a++)this.B[a].n()};k.v=f("A");k.m=function(){return[this.A]};k.remove=function(){this.A.parentNode&&this.A.parentNode.removeChild(this.A)};
k.w=function(a,b){if(!U(this.a,this.a.indexOf(a),b))for(var c=0;c<b.length;c++)this.A.appendChild(b[c])};function La(a,b,c,d){K.call(this,c,d);this.d=a;this.u=b;this.o=m(Ma,a,b);this.H=document.createTextNode(this.o());this.g=!1;this.q=[]}p(La,K);k=La.prototype;k.observe=function(){this.H.textContent=this.o();l(this.r,this);for(var a=0;a<this.d.e.length;a++)this.q.push(M(this.d.e[a]))};k.n=function(){for(var a=0;a<this.d.e.length;a++)N(this.d.e[a]);this.q=[]};k.v=f("H");k.m=function(){return[this.H]};
k.remove=function(){this.H.parentNode&&this.H.parentNode.removeChild(this.H)};k.r=function(){this.g||(this.g=!0,r(v,l(function(){this.g=!1;this.H.textContent=this.o()},this)))};function Ma(a,b){for(var c=[],d=0;d<a.l.length;d++){var e=a.l[d];e instanceof G?c.push(e.C(b)):c.push(e)}return c.join("")}
function Na(a,b,c,d){K.call(this,c,d);this.d=a;this.u=b;this.o=m(Ja,a,b);this.f=[];for(c=0;c<a.p.length;c++){var e=a.p[c];this.f[c]=[];for(var g=e.children.length-1;0<=g;g--){var h=e.children[g];this.f[c][g]=new (T(h))(h,b,this,d)}}this.k=this.o();this.g=!1;this.q=[]}p(Na,K);k=Na.prototype;k.observe=function(){this.k=this.o();for(var a=0;a<this.f.length;a++)for(var b=0;b<this.f[a].length;b++)this.f[a][b].observe();l(this.r,this);for(a=0;a<this.d.e.length;a++)this.q.push(M(this.d.e[a]))};
k.n=function(){for(var a=0;a<this.d.e.length;a++)N(this.d.e[a]);this.q=[];for(a=0;a<this.f.length;a++)for(var b=0;b<this.f[a].length;b++)this.f[a][b].n()};k.m=function(){if(null!=this.k){for(var a=[],b=this.f[this.k],c=0;c<b.length;c++)a.push(b[c].m());return Array.prototype.concat.apply([],a)}return[]};k.v=function(){var a=this.f[this.k];if(a)for(var b=0;b<a.length;b++){var c=a[b].v();if(c)return c}return null};
k.w=function(a,b){var c=this.f[this.k];if(c){var d=c.indexOf(a);-1!=d&&(U(c,d,b)||this.parent.w(this,b))}};k.remove=function(){var a=this.f[this.k];if(a)for(var b=0;b<a.length;b++)a[b].remove()};k.r=function(){this.g||(this.g=!0,r(v,l(function(){this.g=!1;this.W()},this)))};
k.W=function(){var a=this.o();if(a!=this.k){if(null!=this.k)for(var b=this.f[this.k],c=0;c<b.length;c++)b[c].remove();if(null!=a){for(var b=this.f[a],d=[],c=0;c<b.length;c++)Array.prototype.push.apply(d,b[c].m());this.parent.w(this,d)}this.k=a}};function Ja(a,b){for(var c=0;c<a.p.length;c++)if(a.p[c].C(b))return c;return null}
function Pa(a,b,c,d){K.call(this,c,d);this.a=[];this.i=[];this.d=a;var e=this.u=b;for(c=0;c<a.h.length;c++)e=e[a.h[c]];this.t=e;this.Y="";this.M="array_"+Qa++;this.R=this.g=!1;this.L=[];for(c=a.U.length-1;0<=c;c--)e=a.U[c],this.i[c]=new (T(e))(e,b,this,d)}p(Pa,K);k=Pa.prototype;
k.observe=function(){for(var a=this.u,b=0;b<this.d.h.length;b++)a=a[this.d.h[b]];this.t=a;for(b=0;b<this.i.length;b++)this.i[b].observe();this.a=[];Ra(this);for(b=0;b<this.a.length;b++)for(a=0;a<this.a[b].length;a++)this.a[b][a].observe();this.Y=M(this.d.h,l(this.r,this));ka(this.t,l(this.ca,this),this.M)};k.n=function(){N(this.d.h);la(this.M);for(var a=0;a<this.i.length;a++)this.i[a].n();for(a=0;a<this.a.length;a++)for(var b=0;b<this.a[a].length;b++)this.a[a][b].n()};
k.r=function(a){this.g||(this.g=!0,la(this.M),ka(a,l(this.ca,this),this.M),this.t=a,r(v,l(function(){this.g=!1;this.W()},this)))};
k.ca=function(a){Array.prototype.push.apply(this.L,a);this.R||this.g||(this.R=!0,r(v,l(function(){this.R=!1;if(0!=this.L.length&&!this.g){var a=this.L;this.L=[];if(0!=this.a.length||0!=this.t.length)if(0==this.t.length)Sa(this),Ta(this);else if(0==this.a.length)Ua(this),Va(this);else for(var c=0;c<a.length;c++){for(var d=a[c],e=d.addedCount,g=d.removed,h=d=d.index;h<d+g.length;h++)for(var n=0;n<this.a[h].length;n++)this.a[h][n].remove();this.a.splice(d,g.length);g=[];for(h=d;h<d+e;h++){var A=Fa(this.u);
A[this.d.X]=this.t[h];this.a.splice(h,0,[]);g=[];for(n=0;n<this.d.children.length;n++){var q=this.d.children[n];this.a[h][n]=new (T(q))(q,A,this,this.F);this.a[h][n].observe();Array.prototype.push.apply(g,this.a[h][n].m())}}q=this.a[d+e-1];0<g.length&&this.w(q[q.length-1],g)}}},this)))};k.W=function(){this.L=[];if(0!=this.a.length||0!=this.t.length)Sa(this),0==this.t.length?Ta(this):(Ua(this),Va(this))};
function Ta(a){for(var b=[],c=0;c<a.i.length;c++)Array.prototype.push.apply(b,a.i[c].m());a.parent.w(a,b)}function Ua(a){for(var b=0;b<a.i.length;b++)a.i[b].remove()}function Va(a){Ra(a);for(var b=[],c=0;c<a.a.length;c++)for(var d=0;d<a.a[c].length;d++)a.a[c][d].observe(),Array.prototype.push.apply(b,a.a[c][d].m());a.parent.w(a,b)}
function Ra(a){for(var b=0;b<a.t.length;b++){var c=Fa(a.u);c[a.d.X]=a.t[b];a.a[b]=[];for(var d=0;d<a.d.children.length;d++){var e=a.d.children[d];a.a[b][d]=new (T(e))(e,c,a,a.F)}}}function Sa(a){for(var b=0;b<a.a.length;b++)for(var c=0;c<a.a[b].length;c++)a.a[b][c].remove();a.a=[]}
k.m=function(){var a=[];if(0<this.a.length)for(var b=0;b<this.a.length;b++)for(var c=0;c<this.a[b].length;c++)Array.prototype.push.apply(a,this.a[b][c].m());else for(b=0;b<this.i.length;b++)Array.prototype.push.apply(a,this.i[b].m());return a};k.v=function(){if(0<this.a.length)for(var a=0;a<this.a.length;a++)for(var b=0;b<this.a[a].length;b++){var c=this.a[a][b].v();if(c)return c}else for(a=0;a<this.i.length;a++)if(c=this.i[a].v())return c;return null};
k.w=function(a,b){if(0<this.a.length){var c=Array.prototype.concat.apply([],this.a),d=c.indexOf(a);if(-1==d||U(c,d,b))return}else if(d=this.i.indexOf(a),U(this.i,d,b))return;this.parent.w(this,b)};k.remove=function(){if(0<this.a.length)for(var a=0;a<this.a.length;a++)for(var b=0;b<this.a[a].length;b++)this.a[a][b].remove();else for(a=0;a<this.i.length;a++)this.i[a].remove()};
function Wa(a,b,c,d){K.call(this,c,d);this.d=a;this.u=b;if(a.h)for(c=0;c<a.h.length;c++)b=b[a.h[c]];this.D=b;this.s=new x[a.view](this.D);V(this.F,this.s);this.g=!1;this.Y=""}p(Wa,K);k=Wa.prototype;k.observe=function(){var a=this.u;if(this.d.h)for(var b=0;b<this.d.h.length;b++)a=a[this.d.h[b]];this.D!=a&&(Xa(this.F,this.s),this.remove(),this.D=a,this.s=new x[this.d.view](this.D),V(this.F,this.s));this.d.h&&(this.Y=M(this.d.h,l(this.r,this)))};k.n=function(){this.d.h&&N(this.d.h)};k.v=function(){return this.s.j};
k.m=function(){return[this.s.j]};k.remove=function(){var a=this.s.j;a.parentNode&&a.parentNode.removeChild(a)};k.r=function(){this.g||(this.g=!0,r(v,l(function(){this.g=!1;for(var a=this.u,b=0;b<this.d.h.length;b++)a=a[this.d.h[b]];this.D!=a&&(Xa(this.F,this.s),this.remove(),this.D=a,this.s=new x[this.d.view](this.D),V(this.F,this.s),this.parent.w(this,[this.s.j]))},this)))};
function T(a){if(a instanceof C)return S;if(a instanceof D)return La;if(a instanceof F)return Na;if(a instanceof H)return Pa;if(a instanceof ra)return Wa;u("Invalid node of ElementNode, ForeachStmt or IfStmt.")}function U(a,b,c){for(var d=a[++b];d;){if(d=d.v()){if(d.parentNode)for(a=0;a<c.length;a++)d.parentNode.insertBefore(c[a],d);return!0}d=a[++b]}return!1}var Qa=0;function M(a){for(var b="render_"+Qa++,c=0;c<a.length-1;c++);return b}function N(a){for(var b=0;b<a.length-1;b++);};function W(a,b){this.na=a;this.oa=b;this.K=null;this.a=[];this.I=null;this.N=!1;var c=this.oa,d=this.na,e=Ga[c];if(!e){for(e={J:["root"],input:c,Z:0,b:[]};0<e.J.length;){var g=!1,h=e.J[e.J.length-1],n=na[h];n||u("Invalid state: "+h);for(var A=0;A<n.length;A++){var g=n[A],q=e,P=g.c;P.lastIndex=q.Z;var Q=P.exec(q.input);if(Q&&q.Z+Q[0].length==P.lastIndex){for(var R=0;R<g.b.length;R++){var Oa={type:g.b[R]};0==R&&Q[1]&&(Oa.value=Q[1]);q.b.push(Oa)}q.Z=P.lastIndex;g.pop?q.J.pop():g.push&&Array.prototype.push.apply(q.J,
g.push);g=!0}else g=!1;if(g)break}!g&&0<e.J.length&&u("Reached end of rules in state: "+h)}e=e.b;h=e.shift();h=new C(h.value);sa(h,e);e=h;Ga[c]=e}this.I=new S(e,d?{data:d}:{},null,this||null);this.j=this.I.v()}k=W.prototype;k.ja=function(a){X(this);r(v,l(function(){a.appendChild(this.j);ia(this.j)},this))};k.ka=function(a){X(this);r(v,l(function(){a.parentNode.insertBefore(this.j,a);ia(this.j)},this))};
k.remove=function(){Ya(this);r(v,l(function(){var a=this.j;a.parentNode.removeChild(a);var a=this.j,b=ja,c=b.$.indexOf(a),d;for(d in b.aa)a.removeEventListener(d,b.ba,!1);b.$.splice(c,1)},this))};k.ea=function(a){return this.j?this.j.getElementsByClassName(a)[0]:null};k.getParent=f("K");k.appendChild=function(a,b){var c=b||this.j;V(this,a);r(v,function(){c.appendChild(a.j)})};k.ha=function(a,b){V(this,a);r(v,function(){b.parentNode&&b.parentNode.insertBefore(a.j,b)})};
function V(a,b){a.a.push(b);b.K=a;a.N&&X(b)}k.removeChild=function(a){Xa(this,a);var b=a.j;r(v,function(){b.parentNode.removeChild(b)})};function Xa(a,b){a.a.splice(a.a.indexOf(b),1);b.K=null;a.N&&Ya(b)}function X(a){a.N=!0;a.I&&a.I.observe();for(var b=0;b<a.a.length;b++)X(a.a[b])}function Ya(a){a.N=!1;a.I&&a.I.n();for(var b=0;b<a.a.length;b++)Ya(a.a[b])};var Y=["thermo","View"],Z=this;Y[0]in Z||!Z.execScript||Z.execScript("var "+Y[0]);for(var $;Y.length&&($=Y.shift());)Y.length||void 0===W?Z=Z[$]?Z[$]:Z[$]={}:Z[$]=W;W.prototype.render=W.prototype.ja;W.prototype.renderBefore=W.prototype.ka;W.prototype.remove=W.prototype.remove;W.prototype.getElementByClass=W.prototype.ea;W.prototype.getParent=W.prototype.getParent;W.prototype.appendChild=W.prototype.appendChild;W.prototype.insertChildBefore=W.prototype.ha;W.prototype.removeChild=W.prototype.removeChild;
