python2.7 ../closure-library/closure/bin/build/closurebuilder.py \
  --root=../closure-library/ \
  --root=./ \
  --namespace="thermo.api" \
  --output_mode=compiled \
  --compiler_jar=../closure-compiler/compiler.jar \
  --compiler_flags="--compilation_level=ADVANCED_OPTIMIZATIONS" \
  --compiler_flags="--jscomp_error=accessControls" \
  --compiler_flags="--jscomp_error=ambiguousFunctionDecl" \
  --compiler_flags="--jscomp_error=checkDebuggerStatement" \
  --compiler_flags="--jscomp_error=checkRegExp" \
  --compiler_flags="--jscomp_error=checkStructDictInheritance" \
  --compiler_flags="--jscomp_error=checkTypes" \
  --compiler_flags="--jscomp_error=checkVars" \
  --compiler_flags="--jscomp_error=const" \
  --compiler_flags="--jscomp_error=constantProperty" \
  --compiler_flags="--jscomp_error=deprecated" \
  --compiler_flags="--jscomp_error=duplicate" \
  --compiler_flags="--jscomp_error=es5Strict" \
  --compiler_flags="--jscomp_error=externsValidation" \
  --compiler_flags="--jscomp_error=fileoverviewTags" \
  --compiler_flags="--jscomp_error=globalThis" \
  --compiler_flags="--jscomp_error=internetExplorerChecks" \
  --compiler_flags="--jscomp_error=invalidCasts" \
  --compiler_flags="--jscomp_error=missingProperties" \
  --compiler_flags="--jscomp_error=nonStandardJsDocs" \
  --compiler_flags="--jscomp_error=strictModuleDepCheck" \
  --compiler_flags="--jscomp_error=suspiciousCode" \
  --compiler_flags="--jscomp_error=strictModuleDepCheck" \
  --compiler_flags="--jscomp_error=typeInvalidation" \
  --compiler_flags="--jscomp_error=undefinedNames" \
  --compiler_flags="--jscomp_error=undefinedVars" \
  --compiler_flags="--jscomp_error=unknownDefines" \
  --compiler_flags="--jscomp_error=uselessCode" \
  --compiler_flags="--jscomp_error=visibility" \
  --compiler_flags="--externs=../externs/web-animations.js" \
  --compiler_flags="--js=../closure-library/closure/goog/deps.js" \
  > compiled.js
  # Flags which are in code, but don't work, may need to update compiler version.
  #--compiler_flags="--jscomp_error=checkEventfulObjectDisposal" \
  #--compiler_flags="--jscomp_error=missingProvide" \
  #--compiler_flags="--jscomp_error=missingRequire" \
