// This file was autogenerated by ../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../thermo/eventdelegate.js', ['thermo.EventDelegate'], ['goog.asserts']);
goog.addDependency('../../../thermo/eventdelegate_test.js', ['thermo.EventDelegate_test'], ['goog.testing.jsunit', 'goog.testing.recordFunction', 'thermo', 'thermo.EventDelegate']);
goog.addDependency('../../../thermo/model.js', ['thermo.Model'], []);
goog.addDependency('../../../thermo/model_test.js', ['thermo.Model_test'], ['goog.testing.jsunit', 'goog.testing.recordFunction', 'thermo.Model']);
goog.addDependency('../../../thermo/scheduler.js', ['thermo.Scheduler'], ['goog.events']);
goog.addDependency('../../../thermo/thermo.js', ['thermo'], ['thermo.EventDelegate', 'thermo.Scheduler']);
goog.addDependency('../../../thermo/tmpl/lexer.js', ['thermo.tmpl.lexer'], ['goog.asserts']);
goog.addDependency('../../../thermo/tmpl/lexer_test.js', ['thermo.tmpl.lexer_test'], ['goog.testing.jsunit', 'thermo.tmpl.lexer']);
goog.addDependency('../../../thermo/tmpl/parse.js', ['thermo.tmpl.parse'], ['goog.array', 'goog.asserts', 'goog.functions', 'thermo.tmpl.lexer']);
goog.addDependency('../../../thermo/tmpl/parse_test.js', ['thermo.tmpl.parse_test'], ['goog.functions', 'goog.testing.jsunit', 'thermo.tmpl.parse']);
goog.addDependency('../../../thermo/tmpl/render.js', ['thermo.tmpl.render'], ['goog.object', 'thermo', 'thermo.Model', 'thermo.tmpl.parse']);
goog.addDependency('../../../thermo/tmpl/render_test.js', ['thermo.tmpl.render_test'], ['goog.array', 'goog.object', 'goog.testing.dom', 'goog.testing.jsunit', 'thermo', 'thermo.Model', 'thermo.View', 'thermo.tmpl.render']);
goog.addDependency('../../../thermo/view.js', ['thermo.View'], ['thermo', 'thermo.tmpl.render']);
goog.addDependency('../../../thermo/view_test.js', ['thermo.View_test'], ['goog.testing.dom', 'goog.testing.jsunit', 'thermo.View']);
